/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AccountRouteImport } from "./routes/account"
import { Route as CounterRouteImport } from "./routes/counter"
import { Route as DisplayRouteImport } from "./routes/display"
import { Route as KitRouteImport } from "./routes/kit"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as CTokenRouteImport } from "./routes/c.$token"
import { Route as CounterIndexRouteImport } from "./routes/counter.index"
import { Route as CounterReportsRouteImport } from "./routes/counter.reports"
import { Route as CounterScanRouteImport } from "./routes/counter.scan"
import { Route as CounterTradeRouteImport } from "./routes/counter.trade"
import { Route as CounterCustomersIndexRouteImport } from "./routes/counter.customers.index"
import { Route as CounterStockIndexRouteImport } from "./routes/counter.stock.index"
import { Route as CounterStockSkuRouteImport } from "./routes/counter.stock.$sku"
import { Route as CounterStockNewRouteImport } from "./routes/counter.stock.new"
import { Route as CounterCustomersCodeIndexRouteImport } from "./routes/counter.customers.$code.index"
import { Route as CounterCustomersCodeCardRouteImport } from "./routes/counter.customers.$code.card"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => rootRouteImport,
} as any)
const CounterRoute = CounterRouteImport.update({
  id: "/counter",
  path: "/counter",
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayRoute = DisplayRouteImport.update({
  id: "/display",
  path: "/display",
  getParentRoute: () => rootRouteImport,
} as any)
const KitRoute = KitRouteImport.update({
  id: "/kit",
  path: "/kit",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: "/c/$token",
  path: "/c/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const CounterIndexRoute = CounterIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => CounterRoute,
} as any)
const CounterReportsRoute = CounterReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => CounterRoute,
} as any)
const CounterScanRoute = CounterScanRouteImport.update({
  id: "/scan",
  path: "/scan",
  getParentRoute: () => CounterRoute,
} as any)
const CounterTradeRoute = CounterTradeRouteImport.update({
  id: "/trade",
  path: "/trade",
  getParentRoute: () => CounterRoute,
} as any)
const CounterCustomersIndexRoute = CounterCustomersIndexRouteImport.update({
  id: "/customers/",
  path: "/customers/",
  getParentRoute: () => CounterRoute,
} as any)
const CounterStockIndexRoute = CounterStockIndexRouteImport.update({
  id: "/stock/",
  path: "/stock/",
  getParentRoute: () => CounterRoute,
} as any)
const CounterStockSkuRoute = CounterStockSkuRouteImport.update({
  id: "/stock/$sku",
  path: "/stock/$sku",
  getParentRoute: () => CounterRoute,
} as any)
const CounterStockNewRoute = CounterStockNewRouteImport.update({
  id: "/stock/new",
  path: "/stock/new",
  getParentRoute: () => CounterRoute,
} as any)
const CounterCustomersCodeIndexRoute =
  CounterCustomersCodeIndexRouteImport.update({
    id: "/customers/$code/",
    path: "/customers/$code/",
    getParentRoute: () => CounterRoute,
  } as any)
const CounterCustomersCodeCardRoute =
  CounterCustomersCodeCardRouteImport.update({
    id: "/customers/$code/card",
    path: "/customers/$code/card",
    getParentRoute: () => CounterRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/account": typeof AccountRoute
  "/counter": typeof CounterRouteWithChildren
  "/display": typeof DisplayRoute
  "/kit": typeof KitRoute
  "/login": typeof LoginRoute
  "/c/$token": typeof CTokenRoute
  "/counter/reports": typeof CounterReportsRoute
  "/counter/scan": typeof CounterScanRoute
  "/counter/trade": typeof CounterTradeRoute
  "/counter/": typeof CounterIndexRoute
  "/counter/stock/$sku": typeof CounterStockSkuRoute
  "/counter/stock/new": typeof CounterStockNewRoute
  "/counter/customers/": typeof CounterCustomersIndexRoute
  "/counter/stock/": typeof CounterStockIndexRoute
  "/counter/customers/$code/card": typeof CounterCustomersCodeCardRoute
  "/counter/customers/$code/": typeof CounterCustomersCodeIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/account": typeof AccountRoute
  "/display": typeof DisplayRoute
  "/kit": typeof KitRoute
  "/login": typeof LoginRoute
  "/c/$token": typeof CTokenRoute
  "/counter/reports": typeof CounterReportsRoute
  "/counter/scan": typeof CounterScanRoute
  "/counter/trade": typeof CounterTradeRoute
  "/counter": typeof CounterIndexRoute
  "/counter/stock/$sku": typeof CounterStockSkuRoute
  "/counter/stock/new": typeof CounterStockNewRoute
  "/counter/customers": typeof CounterCustomersIndexRoute
  "/counter/stock": typeof CounterStockIndexRoute
  "/counter/customers/$code/card": typeof CounterCustomersCodeCardRoute
  "/counter/customers/$code": typeof CounterCustomersCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/account": typeof AccountRoute
  "/counter": typeof CounterRouteWithChildren
  "/display": typeof DisplayRoute
  "/kit": typeof KitRoute
  "/login": typeof LoginRoute
  "/c/$token": typeof CTokenRoute
  "/counter/reports": typeof CounterReportsRoute
  "/counter/scan": typeof CounterScanRoute
  "/counter/trade": typeof CounterTradeRoute
  "/counter/": typeof CounterIndexRoute
  "/counter/stock/$sku": typeof CounterStockSkuRoute
  "/counter/stock/new": typeof CounterStockNewRoute
  "/counter/customers/": typeof CounterCustomersIndexRoute
  "/counter/stock/": typeof CounterStockIndexRoute
  "/counter/customers/$code/card": typeof CounterCustomersCodeCardRoute
  "/counter/customers/$code/": typeof CounterCustomersCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/account"
    | "/counter"
    | "/display"
    | "/kit"
    | "/login"
    | "/c/$token"
    | "/counter/reports"
    | "/counter/scan"
    | "/counter/trade"
    | "/counter/"
    | "/counter/stock/$sku"
    | "/counter/stock/new"
    | "/counter/customers/"
    | "/counter/stock/"
    | "/counter/customers/$code/card"
    | "/counter/customers/$code/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/account"
    | "/display"
    | "/kit"
    | "/login"
    | "/c/$token"
    | "/counter/reports"
    | "/counter/scan"
    | "/counter/trade"
    | "/counter"
    | "/counter/stock/$sku"
    | "/counter/stock/new"
    | "/counter/customers"
    | "/counter/stock"
    | "/counter/customers/$code/card"
    | "/counter/customers/$code"
  id:
    | "__root__"
    | "/"
    | "/account"
    | "/counter"
    | "/display"
    | "/kit"
    | "/login"
    | "/c/$token"
    | "/counter/reports"
    | "/counter/scan"
    | "/counter/trade"
    | "/counter/"
    | "/counter/stock/$sku"
    | "/counter/stock/new"
    | "/counter/customers/"
    | "/counter/stock/"
    | "/counter/customers/$code/card"
    | "/counter/customers/$code/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CounterRoute: typeof CounterRouteWithChildren
  DisplayRoute: typeof DisplayRoute
  KitRoute: typeof KitRoute
  LoginRoute: typeof LoginRoute
  CTokenRoute: typeof CTokenRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/account": {
      id: "/account"
      path: "/account"
      fullPath: "/account"
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/counter": {
      id: "/counter"
      path: "/counter"
      fullPath: "/counter"
      preLoaderRoute: typeof CounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/display": {
      id: "/display"
      path: "/display"
      fullPath: "/display"
      preLoaderRoute: typeof DisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/kit": {
      id: "/kit"
      path: "/kit"
      fullPath: "/kit"
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/c/$token": {
      id: "/c/$token"
      path: "/c/$token"
      fullPath: "/c/$token"
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/counter/": {
      id: "/counter/"
      path: "/"
      fullPath: "/counter/"
      preLoaderRoute: typeof CounterIndexRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/reports": {
      id: "/counter/reports"
      path: "/reports"
      fullPath: "/counter/reports"
      preLoaderRoute: typeof CounterReportsRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/scan": {
      id: "/counter/scan"
      path: "/scan"
      fullPath: "/counter/scan"
      preLoaderRoute: typeof CounterScanRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/trade": {
      id: "/counter/trade"
      path: "/trade"
      fullPath: "/counter/trade"
      preLoaderRoute: typeof CounterTradeRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/customers/": {
      id: "/counter/customers/"
      path: "/customers"
      fullPath: "/counter/customers/"
      preLoaderRoute: typeof CounterCustomersIndexRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/stock/": {
      id: "/counter/stock/"
      path: "/stock"
      fullPath: "/counter/stock/"
      preLoaderRoute: typeof CounterStockIndexRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/stock/$sku": {
      id: "/counter/stock/$sku"
      path: "/stock/$sku"
      fullPath: "/counter/stock/$sku"
      preLoaderRoute: typeof CounterStockSkuRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/stock/new": {
      id: "/counter/stock/new"
      path: "/stock/new"
      fullPath: "/counter/stock/new"
      preLoaderRoute: typeof CounterStockNewRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/customers/$code/": {
      id: "/counter/customers/$code/"
      path: "/customers/$code"
      fullPath: "/counter/customers/$code/"
      preLoaderRoute: typeof CounterCustomersCodeIndexRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/customers/$code/card": {
      id: "/counter/customers/$code/card"
      path: "/customers/$code/card"
      fullPath: "/counter/customers/$code/card"
      preLoaderRoute: typeof CounterCustomersCodeCardRouteImport
      parentRoute: typeof CounterRoute
    }
  }
}

interface CounterRouteChildren {
  CounterReportsRoute: typeof CounterReportsRoute
  CounterScanRoute: typeof CounterScanRoute
  CounterTradeRoute: typeof CounterTradeRoute
  CounterIndexRoute: typeof CounterIndexRoute
  CounterStockSkuRoute: typeof CounterStockSkuRoute
  CounterStockNewRoute: typeof CounterStockNewRoute
  CounterCustomersIndexRoute: typeof CounterCustomersIndexRoute
  CounterStockIndexRoute: typeof CounterStockIndexRoute
  CounterCustomersCodeCardRoute: typeof CounterCustomersCodeCardRoute
  CounterCustomersCodeIndexRoute: typeof CounterCustomersCodeIndexRoute
}

const CounterRouteChildren: CounterRouteChildren = {
  CounterReportsRoute: CounterReportsRoute,
  CounterScanRoute: CounterScanRoute,
  CounterTradeRoute: CounterTradeRoute,
  CounterIndexRoute: CounterIndexRoute,
  CounterStockSkuRoute: CounterStockSkuRoute,
  CounterStockNewRoute: CounterStockNewRoute,
  CounterCustomersIndexRoute: CounterCustomersIndexRoute,
  CounterStockIndexRoute: CounterStockIndexRoute,
  CounterCustomersCodeCardRoute: CounterCustomersCodeCardRoute,
  CounterCustomersCodeIndexRoute: CounterCustomersCodeIndexRoute,
}

const CounterRouteWithChildren =
  CounterRoute._addFileChildren(CounterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CounterRoute: CounterRouteWithChildren,
  DisplayRoute: DisplayRoute,
  KitRoute: KitRoute,
  LoginRoute: LoginRoute,
  CTokenRoute: CTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
