/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AccountRouteImport } from "./routes/account"
import { Route as CounterRouteImport } from "./routes/counter"
import { Route as DisplayRouteImport } from "./routes/display"
import { Route as KitRouteImport } from "./routes/kit"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as CTokenRouteImport } from "./routes/c.$token"
import { Route as CounterIndexRouteImport } from "./routes/counter.index"
import { Route as CounterCashRouteImport } from "./routes/counter.cash"
import { Route as CounterLabelsRouteImport } from "./routes/counter.labels"
import { Route as CounterReportsRouteImport } from "./routes/counter.reports"
import { Route as CounterScanRouteImport } from "./routes/counter.scan"
import { Route as CounterSellRouteImport } from "./routes/counter.sell"
import { Route as CounterSettingsRouteImport } from "./routes/counter.settings"
import { Route as LabelsPrintRouteImport } from "./routes/labels.print"
import { Route as CounterCustomersIndexRouteImport } from "./routes/counter.customers.index"
import { Route as CounterCustomersNewRouteImport } from "./routes/counter.customers.new"
import { Route as CounterStockIndexRouteImport } from "./routes/counter.stock.index"
import { Route as CounterStockSkuRouteImport } from "./routes/counter.stock.$sku"
import { Route as CounterStockNewRouteImport } from "./routes/counter.stock.new"
import { Route as CounterTradeIndexRouteImport } from "./routes/counter.trade.index"
import { Route as CounterTradeNewRouteImport } from "./routes/counter.trade.new"
import { Route as CounterCustomersCodeIndexRouteImport } from "./routes/counter.customers.$code.index"
import { Route as CounterCustomersCodeCardRouteImport } from "./routes/counter.customers.$code.card"
import { Route as CounterStockCountIndexRouteImport } from "./routes/counter.stock.count.index"
import { Route as CounterStockCountIdRouteImport } from "./routes/counter.stock.count.$id"
import { Route as CounterTradeIdIndexRouteImport } from "./routes/counter.trade.$id.index"
import { Route as CounterTradeIdReceiptRouteImport } from "./routes/counter.trade.$id.receipt"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => rootRouteImport,
} as any)
const CounterRoute = CounterRouteImport.update({
  id: "/counter",
  path: "/counter",
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayRoute = DisplayRouteImport.update({
  id: "/display",
  path: "/display",
  getParentRoute: () => rootRouteImport,
} as any)
const KitRoute = KitRouteImport.update({
  id: "/kit",
  path: "/kit",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: "/c/$token",
  path: "/c/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const CounterIndexRoute = CounterIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => CounterRoute,
} as any)
const CounterCashRoute = CounterCashRouteImport.update({
  id: "/cash",
  path: "/cash",
  getParentRoute: () => CounterRoute,
} as any)
const CounterLabelsRoute = CounterLabelsRouteImport.update({
  id: "/labels",
  path: "/labels",
  getParentRoute: () => CounterRoute,
} as any)
const CounterReportsRoute = CounterReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => CounterRoute,
} as any)
const CounterScanRoute = CounterScanRouteImport.update({
  id: "/scan",
  path: "/scan",
  getParentRoute: () => CounterRoute,
} as any)
const CounterSellRoute = CounterSellRouteImport.update({
  id: "/sell",
  path: "/sell",
  getParentRoute: () => CounterRoute,
} as any)
const CounterSettingsRoute = CounterSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => CounterRoute,
} as any)
const LabelsPrintRoute = LabelsPrintRouteImport.update({
  id: "/labels/print",
  path: "/labels/print",
  getParentRoute: () => rootRouteImport,
} as any)
const CounterCustomersIndexRoute = CounterCustomersIndexRouteImport.update({
  id: "/customers/",
  path: "/customers/",
  getParentRoute: () => CounterRoute,
} as any)
const CounterCustomersNewRoute = CounterCustomersNewRouteImport.update({
  id: "/customers/new",
  path: "/customers/new",
  getParentRoute: () => CounterRoute,
} as any)
const CounterStockIndexRoute = CounterStockIndexRouteImport.update({
  id: "/stock/",
  path: "/stock/",
  getParentRoute: () => CounterRoute,
} as any)
const CounterStockSkuRoute = CounterStockSkuRouteImport.update({
  id: "/stock/$sku",
  path: "/stock/$sku",
  getParentRoute: () => CounterRoute,
} as any)
const CounterStockNewRoute = CounterStockNewRouteImport.update({
  id: "/stock/new",
  path: "/stock/new",
  getParentRoute: () => CounterRoute,
} as any)
const CounterTradeIndexRoute = CounterTradeIndexRouteImport.update({
  id: "/trade/",
  path: "/trade/",
  getParentRoute: () => CounterRoute,
} as any)
const CounterTradeNewRoute = CounterTradeNewRouteImport.update({
  id: "/trade/new",
  path: "/trade/new",
  getParentRoute: () => CounterRoute,
} as any)
const CounterCustomersCodeIndexRoute =
  CounterCustomersCodeIndexRouteImport.update({
    id: "/customers/$code/",
    path: "/customers/$code/",
    getParentRoute: () => CounterRoute,
  } as any)
const CounterCustomersCodeCardRoute =
  CounterCustomersCodeCardRouteImport.update({
    id: "/customers/$code/card",
    path: "/customers/$code/card",
    getParentRoute: () => CounterRoute,
  } as any)
const CounterStockCountIndexRoute = CounterStockCountIndexRouteImport.update({
  id: "/stock/count/",
  path: "/stock/count/",
  getParentRoute: () => CounterRoute,
} as any)
const CounterStockCountIdRoute = CounterStockCountIdRouteImport.update({
  id: "/stock/count/$id",
  path: "/stock/count/$id",
  getParentRoute: () => CounterRoute,
} as any)
const CounterTradeIdIndexRoute = CounterTradeIdIndexRouteImport.update({
  id: "/trade/$id/",
  path: "/trade/$id/",
  getParentRoute: () => CounterRoute,
} as any)
const CounterTradeIdReceiptRoute = CounterTradeIdReceiptRouteImport.update({
  id: "/trade/$id/receipt",
  path: "/trade/$id/receipt",
  getParentRoute: () => CounterRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/account": typeof AccountRoute
  "/counter": typeof CounterRouteWithChildren
  "/display": typeof DisplayRoute
  "/kit": typeof KitRoute
  "/login": typeof LoginRoute
  "/c/$token": typeof CTokenRoute
  "/counter/cash": typeof CounterCashRoute
  "/counter/labels": typeof CounterLabelsRoute
  "/counter/reports": typeof CounterReportsRoute
  "/counter/scan": typeof CounterScanRoute
  "/counter/sell": typeof CounterSellRoute
  "/counter/settings": typeof CounterSettingsRoute
  "/labels/print": typeof LabelsPrintRoute
  "/counter/": typeof CounterIndexRoute
  "/counter/customers/new": typeof CounterCustomersNewRoute
  "/counter/stock/$sku": typeof CounterStockSkuRoute
  "/counter/stock/new": typeof CounterStockNewRoute
  "/counter/trade/new": typeof CounterTradeNewRoute
  "/counter/customers/": typeof CounterCustomersIndexRoute
  "/counter/stock/": typeof CounterStockIndexRoute
  "/counter/trade/": typeof CounterTradeIndexRoute
  "/counter/customers/$code/card": typeof CounterCustomersCodeCardRoute
  "/counter/stock/count/$id": typeof CounterStockCountIdRoute
  "/counter/trade/$id/receipt": typeof CounterTradeIdReceiptRoute
  "/counter/customers/$code/": typeof CounterCustomersCodeIndexRoute
  "/counter/stock/count/": typeof CounterStockCountIndexRoute
  "/counter/trade/$id/": typeof CounterTradeIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/account": typeof AccountRoute
  "/display": typeof DisplayRoute
  "/kit": typeof KitRoute
  "/login": typeof LoginRoute
  "/c/$token": typeof CTokenRoute
  "/counter/cash": typeof CounterCashRoute
  "/counter/labels": typeof CounterLabelsRoute
  "/counter/reports": typeof CounterReportsRoute
  "/counter/scan": typeof CounterScanRoute
  "/counter/sell": typeof CounterSellRoute
  "/counter/settings": typeof CounterSettingsRoute
  "/labels/print": typeof LabelsPrintRoute
  "/counter": typeof CounterIndexRoute
  "/counter/customers/new": typeof CounterCustomersNewRoute
  "/counter/stock/$sku": typeof CounterStockSkuRoute
  "/counter/stock/new": typeof CounterStockNewRoute
  "/counter/trade/new": typeof CounterTradeNewRoute
  "/counter/customers": typeof CounterCustomersIndexRoute
  "/counter/stock": typeof CounterStockIndexRoute
  "/counter/trade": typeof CounterTradeIndexRoute
  "/counter/customers/$code/card": typeof CounterCustomersCodeCardRoute
  "/counter/stock/count/$id": typeof CounterStockCountIdRoute
  "/counter/trade/$id/receipt": typeof CounterTradeIdReceiptRoute
  "/counter/customers/$code": typeof CounterCustomersCodeIndexRoute
  "/counter/stock/count": typeof CounterStockCountIndexRoute
  "/counter/trade/$id": typeof CounterTradeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/account": typeof AccountRoute
  "/counter": typeof CounterRouteWithChildren
  "/display": typeof DisplayRoute
  "/kit": typeof KitRoute
  "/login": typeof LoginRoute
  "/c/$token": typeof CTokenRoute
  "/counter/cash": typeof CounterCashRoute
  "/counter/labels": typeof CounterLabelsRoute
  "/counter/reports": typeof CounterReportsRoute
  "/counter/scan": typeof CounterScanRoute
  "/counter/sell": typeof CounterSellRoute
  "/counter/settings": typeof CounterSettingsRoute
  "/labels/print": typeof LabelsPrintRoute
  "/counter/": typeof CounterIndexRoute
  "/counter/customers/new": typeof CounterCustomersNewRoute
  "/counter/stock/$sku": typeof CounterStockSkuRoute
  "/counter/stock/new": typeof CounterStockNewRoute
  "/counter/trade/new": typeof CounterTradeNewRoute
  "/counter/customers/": typeof CounterCustomersIndexRoute
  "/counter/stock/": typeof CounterStockIndexRoute
  "/counter/trade/": typeof CounterTradeIndexRoute
  "/counter/customers/$code/card": typeof CounterCustomersCodeCardRoute
  "/counter/stock/count/$id": typeof CounterStockCountIdRoute
  "/counter/trade/$id/receipt": typeof CounterTradeIdReceiptRoute
  "/counter/customers/$code/": typeof CounterCustomersCodeIndexRoute
  "/counter/stock/count/": typeof CounterStockCountIndexRoute
  "/counter/trade/$id/": typeof CounterTradeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/account"
    | "/counter"
    | "/display"
    | "/kit"
    | "/login"
    | "/c/$token"
    | "/counter/cash"
    | "/counter/labels"
    | "/counter/reports"
    | "/counter/scan"
    | "/counter/sell"
    | "/counter/settings"
    | "/labels/print"
    | "/counter/"
    | "/counter/customers/new"
    | "/counter/stock/$sku"
    | "/counter/stock/new"
    | "/counter/trade/new"
    | "/counter/customers/"
    | "/counter/stock/"
    | "/counter/trade/"
    | "/counter/customers/$code/card"
    | "/counter/stock/count/$id"
    | "/counter/trade/$id/receipt"
    | "/counter/customers/$code/"
    | "/counter/stock/count/"
    | "/counter/trade/$id/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/account"
    | "/display"
    | "/kit"
    | "/login"
    | "/c/$token"
    | "/counter/cash"
    | "/counter/labels"
    | "/counter/reports"
    | "/counter/scan"
    | "/counter/sell"
    | "/counter/settings"
    | "/labels/print"
    | "/counter"
    | "/counter/customers/new"
    | "/counter/stock/$sku"
    | "/counter/stock/new"
    | "/counter/trade/new"
    | "/counter/customers"
    | "/counter/stock"
    | "/counter/trade"
    | "/counter/customers/$code/card"
    | "/counter/stock/count/$id"
    | "/counter/trade/$id/receipt"
    | "/counter/customers/$code"
    | "/counter/stock/count"
    | "/counter/trade/$id"
  id:
    | "__root__"
    | "/"
    | "/account"
    | "/counter"
    | "/display"
    | "/kit"
    | "/login"
    | "/c/$token"
    | "/counter/cash"
    | "/counter/labels"
    | "/counter/reports"
    | "/counter/scan"
    | "/counter/sell"
    | "/counter/settings"
    | "/labels/print"
    | "/counter/"
    | "/counter/customers/new"
    | "/counter/stock/$sku"
    | "/counter/stock/new"
    | "/counter/trade/new"
    | "/counter/customers/"
    | "/counter/stock/"
    | "/counter/trade/"
    | "/counter/customers/$code/card"
    | "/counter/stock/count/$id"
    | "/counter/trade/$id/receipt"
    | "/counter/customers/$code/"
    | "/counter/stock/count/"
    | "/counter/trade/$id/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CounterRoute: typeof CounterRouteWithChildren
  DisplayRoute: typeof DisplayRoute
  KitRoute: typeof KitRoute
  LoginRoute: typeof LoginRoute
  CTokenRoute: typeof CTokenRoute
  LabelsPrintRoute: typeof LabelsPrintRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/account": {
      id: "/account"
      path: "/account"
      fullPath: "/account"
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/counter": {
      id: "/counter"
      path: "/counter"
      fullPath: "/counter"
      preLoaderRoute: typeof CounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/display": {
      id: "/display"
      path: "/display"
      fullPath: "/display"
      preLoaderRoute: typeof DisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/kit": {
      id: "/kit"
      path: "/kit"
      fullPath: "/kit"
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/c/$token": {
      id: "/c/$token"
      path: "/c/$token"
      fullPath: "/c/$token"
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/counter/": {
      id: "/counter/"
      path: "/"
      fullPath: "/counter/"
      preLoaderRoute: typeof CounterIndexRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/cash": {
      id: "/counter/cash"
      path: "/cash"
      fullPath: "/counter/cash"
      preLoaderRoute: typeof CounterCashRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/labels": {
      id: "/counter/labels"
      path: "/labels"
      fullPath: "/counter/labels"
      preLoaderRoute: typeof CounterLabelsRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/reports": {
      id: "/counter/reports"
      path: "/reports"
      fullPath: "/counter/reports"
      preLoaderRoute: typeof CounterReportsRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/scan": {
      id: "/counter/scan"
      path: "/scan"
      fullPath: "/counter/scan"
      preLoaderRoute: typeof CounterScanRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/sell": {
      id: "/counter/sell"
      path: "/sell"
      fullPath: "/counter/sell"
      preLoaderRoute: typeof CounterSellRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/settings": {
      id: "/counter/settings"
      path: "/settings"
      fullPath: "/counter/settings"
      preLoaderRoute: typeof CounterSettingsRouteImport
      parentRoute: typeof CounterRoute
    }
    "/labels/print": {
      id: "/labels/print"
      path: "/labels/print"
      fullPath: "/labels/print"
      preLoaderRoute: typeof LabelsPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/counter/customers/": {
      id: "/counter/customers/"
      path: "/customers"
      fullPath: "/counter/customers/"
      preLoaderRoute: typeof CounterCustomersIndexRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/customers/new": {
      id: "/counter/customers/new"
      path: "/customers/new"
      fullPath: "/counter/customers/new"
      preLoaderRoute: typeof CounterCustomersNewRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/stock/": {
      id: "/counter/stock/"
      path: "/stock"
      fullPath: "/counter/stock/"
      preLoaderRoute: typeof CounterStockIndexRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/stock/$sku": {
      id: "/counter/stock/$sku"
      path: "/stock/$sku"
      fullPath: "/counter/stock/$sku"
      preLoaderRoute: typeof CounterStockSkuRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/stock/new": {
      id: "/counter/stock/new"
      path: "/stock/new"
      fullPath: "/counter/stock/new"
      preLoaderRoute: typeof CounterStockNewRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/trade/": {
      id: "/counter/trade/"
      path: "/trade"
      fullPath: "/counter/trade/"
      preLoaderRoute: typeof CounterTradeIndexRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/trade/new": {
      id: "/counter/trade/new"
      path: "/trade/new"
      fullPath: "/counter/trade/new"
      preLoaderRoute: typeof CounterTradeNewRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/customers/$code/": {
      id: "/counter/customers/$code/"
      path: "/customers/$code"
      fullPath: "/counter/customers/$code/"
      preLoaderRoute: typeof CounterCustomersCodeIndexRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/customers/$code/card": {
      id: "/counter/customers/$code/card"
      path: "/customers/$code/card"
      fullPath: "/counter/customers/$code/card"
      preLoaderRoute: typeof CounterCustomersCodeCardRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/stock/count/": {
      id: "/counter/stock/count/"
      path: "/stock/count"
      fullPath: "/counter/stock/count/"
      preLoaderRoute: typeof CounterStockCountIndexRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/stock/count/$id": {
      id: "/counter/stock/count/$id"
      path: "/stock/count/$id"
      fullPath: "/counter/stock/count/$id"
      preLoaderRoute: typeof CounterStockCountIdRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/trade/$id/": {
      id: "/counter/trade/$id/"
      path: "/trade/$id"
      fullPath: "/counter/trade/$id/"
      preLoaderRoute: typeof CounterTradeIdIndexRouteImport
      parentRoute: typeof CounterRoute
    }
    "/counter/trade/$id/receipt": {
      id: "/counter/trade/$id/receipt"
      path: "/trade/$id/receipt"
      fullPath: "/counter/trade/$id/receipt"
      preLoaderRoute: typeof CounterTradeIdReceiptRouteImport
      parentRoute: typeof CounterRoute
    }
  }
}

interface CounterRouteChildren {
  CounterCashRoute: typeof CounterCashRoute
  CounterLabelsRoute: typeof CounterLabelsRoute
  CounterReportsRoute: typeof CounterReportsRoute
  CounterScanRoute: typeof CounterScanRoute
  CounterSellRoute: typeof CounterSellRoute
  CounterSettingsRoute: typeof CounterSettingsRoute
  CounterIndexRoute: typeof CounterIndexRoute
  CounterCustomersNewRoute: typeof CounterCustomersNewRoute
  CounterStockSkuRoute: typeof CounterStockSkuRoute
  CounterStockNewRoute: typeof CounterStockNewRoute
  CounterTradeNewRoute: typeof CounterTradeNewRoute
  CounterCustomersIndexRoute: typeof CounterCustomersIndexRoute
  CounterStockIndexRoute: typeof CounterStockIndexRoute
  CounterTradeIndexRoute: typeof CounterTradeIndexRoute
  CounterCustomersCodeCardRoute: typeof CounterCustomersCodeCardRoute
  CounterStockCountIdRoute: typeof CounterStockCountIdRoute
  CounterTradeIdReceiptRoute: typeof CounterTradeIdReceiptRoute
  CounterCustomersCodeIndexRoute: typeof CounterCustomersCodeIndexRoute
  CounterStockCountIndexRoute: typeof CounterStockCountIndexRoute
  CounterTradeIdIndexRoute: typeof CounterTradeIdIndexRoute
}

const CounterRouteChildren: CounterRouteChildren = {
  CounterCashRoute: CounterCashRoute,
  CounterLabelsRoute: CounterLabelsRoute,
  CounterReportsRoute: CounterReportsRoute,
  CounterScanRoute: CounterScanRoute,
  CounterSellRoute: CounterSellRoute,
  CounterSettingsRoute: CounterSettingsRoute,
  CounterIndexRoute: CounterIndexRoute,
  CounterCustomersNewRoute: CounterCustomersNewRoute,
  CounterStockSkuRoute: CounterStockSkuRoute,
  CounterStockNewRoute: CounterStockNewRoute,
  CounterTradeNewRoute: CounterTradeNewRoute,
  CounterCustomersIndexRoute: CounterCustomersIndexRoute,
  CounterStockIndexRoute: CounterStockIndexRoute,
  CounterTradeIndexRoute: CounterTradeIndexRoute,
  CounterCustomersCodeCardRoute: CounterCustomersCodeCardRoute,
  CounterStockCountIdRoute: CounterStockCountIdRoute,
  CounterTradeIdReceiptRoute: CounterTradeIdReceiptRoute,
  CounterCustomersCodeIndexRoute: CounterCustomersCodeIndexRoute,
  CounterStockCountIndexRoute: CounterStockCountIndexRoute,
  CounterTradeIdIndexRoute: CounterTradeIdIndexRoute,
}

const CounterRouteWithChildren =
  CounterRoute._addFileChildren(CounterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CounterRoute: CounterRouteWithChildren,
  DisplayRoute: DisplayRoute,
  KitRoute: KitRoute,
  LoginRoute: LoginRoute,
  CTokenRoute: CTokenRoute,
  LabelsPrintRoute: LabelsPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
