// GENERATED BY HAND, NOT BY A BUILD STEP - an ordinary CommonJS module
// (pb_hooks cannot load TypeScript; see CLAUDE.md's "Hooks").
//
// Epos Now's v4 REST API, the five calls GG Vault makes:
//
//   POST v4/Customer                      create the till's customer
//   GET  v4/Customer/GetByEmail?email=    find one we may already have made
//   GET  v4/Customer/{id}                 read a customer's card number
//   GET  v4/Transaction/{id}?extended=    one sale, items and all
//   GET  v4/Transaction/GetByDate?...     a day's completed sales, 200 a page
//
// Auth is `Authorization: Basic <token>`, the token being the one Epos Now
// Back Office issues for an API device, stored in `settings.api_keys.eposnow`
// and never sent anywhere but here. Every call goes through adapters/http.js,
// so pb/scripts/check.sh's fixture transport answers it under test and a
// real request falls through to $http.send.
//
// Nothing here throws for an HTTP failure: every call answers
// `{ ok, status, data, message }`, because Epos Now being down is an
// ordinary thing that the callers queue and retry rather than a crash.
// The token never appears in a message or a log line, and neither does a
// customer's email address (adapters/http.js's `stripQuery`).
"use strict";

var BASE_URL = "https://api.eposnowhq.com/api/";

/** A short timeout: a sign-up or a Guild join is never held up for long. */
var TIMEOUT_SECONDS = 8;

function call(cfg, method, path, body) {
  var http = require(__hooks + "/adapters/http.js");
  if (!cfg || !cfg.token) {
    return { ok: false, status: 0, data: null, message: "Epos Now is not set up: there is no API token." };
  }
  var req = {
    url: BASE_URL + path,
    method: method,
    headers: {
      Authorization: "Basic " + cfg.token,
      Accept: "application/json",
    },
    timeoutSeconds: TIMEOUT_SECONDS,
  };
  if (body !== undefined) {
    req.headers["Content-Type"] = "application/json";
    req.body = JSON.stringify(body);
  }
  var res;
  try {
    res = http.request(req);
  } catch (err) {
    return {
      ok: false,
      status: 0,
      data: null,
      message: "Epos Now could not be reached (" + http.stripQuery(String(err)).slice(0, 160) + ").",
    };
  }
  var status = res && res.statusCode ? res.statusCode : 0;
  var data = res ? res.json : null;
  if (status >= 200 && status < 300) {
    return { ok: true, status: status, data: data, message: "" };
  }
  return {
    ok: false,
    status: status,
    data: data,
    message: "Epos Now answered " + status + " to " + method + " " + http.stripQuery(path) + ".",
  };
}

function createCustomer(cfg, body) {
  return call(cfg, "POST", "v4/Customer", body);
}

function findCustomersByEmail(cfg, email) {
  var http = require(__hooks + "/adapters/http.js");
  return call(cfg, "GET", "v4/Customer/GetByEmail?" + http.qs({ email: email }));
}

function getCustomer(cfg, id) {
  return call(cfg, "GET", "v4/Customer/" + encodeURIComponent(String(id)));
}

/**
 * One transaction with its items. The webhook never trusts the sale a
 * request body describes: it reads the sale back from Epos Now with our
 * own token, so a leaked webhook URL can only ever make GG Vault look at a
 * real sale again.
 */
function getTransaction(cfg, id) {
  return call(
    cfg,
    "GET",
    "v4/Transaction/" + encodeURIComponent(String(id)) + "?extended=true&lockTransaction=false"
  );
}

/**
 * One page of completed transactions between two zone-less UTC times
 * (`2026-10-06T00:00:00`), with their items (`extended=true`).
 */
function transactionsByDate(cfg, start, end, page) {
  var http = require(__hooks + "/adapters/http.js");
  return call(
    cfg,
    "GET",
    "v4/Transaction/GetByDate?" +
      http.qs({ startDate: start, endDate: end, status: 1, extended: "true", page: page || 1 })
  );
}

module.exports = {
  BASE_URL: BASE_URL,
  createCustomer: createCustomer,
  findCustomersByEmail: findCustomersByEmail,
  getCustomer: getCustomer,
  getTransaction: getTransaction,
  transactionsByDate: transactionsByDate,
};
