// GENERATED BY HAND, NOT BY A BUILD STEP - this is an ordinary CommonJS
// module (pb_hooks cannot load TypeScript; see CLAUDE.md's "Hooks").
//
// Shared outbound HTTP helper for every adapter in this directory. Every
// adapter requires this file fresh, inside its own function body, exactly
// like every other pb_hooks module (pb/README.md: a handler runs in its
// own isolated goja context, so anything required at file top level in the
// *hook* file itself is not visible at request time; a module's own
// top-level declarations are fine, because require() re-evaluates the
// whole module inside the caller's request).
//
// Overridable for tests, two ways, per the brief ("a module-level `http`
// function must be overridable for tests"):
//   1. Pass a `transport` function as the last argument to `request()`.
//   2. Set `globalThis.__adapterTransport` before calling in (what
//      pb/scripts/check-adapters.mjs does, since it requires each adapter
//      fresh per test and has no other way to reach inside it).
// A goja request never sees either: every hook request is a fresh
// isolated context (pb/README.md), so `globalThis.__adapterTransport` is
// never set there and every real request falls through to $http.send.
//
// GG_ADAPTER_TRANSPORT_MODE=offline_fail is the switch pb/scripts/check.sh
// runs its whole server under: any attempt to reach the real network
// throws immediately with a message naming the call, so a route that is
// supposed to serve straight from the database (a fresh cached lookup, the
// uk-comp write, the prices read) fails loudly instead of silently making
// a live call an end-to-end test cannot see.
"use strict";

var USER_AGENT = "GGVault/1.0 (+https://vault.ggentertainment.co.uk)";
var DEFAULT_TIMEOUT_SECONDS = 20;

// Every adapter requires its neighbours the same way the rest of pb_hooks
// does - `require(`${__hooks}/adapters/http.js`)`, `require(`${__hooks}/lib/shared/money.js`)`
// - because `__hooks` is a real global inside PocketBase (the absolute path
// to pb_hooks) and pb/scripts/check-adapters.mjs sets `global.__hooks` to
// that same directory's real path before requiring any adapter under plain
// Node, so the identical require() call resolves in both places. Node's own
// require() accepts an absolute path directly, so there is no
// relative-path resolution to get right across two different module
// loaders.

/**
 * @param {{url:string, method?:string, headers?:object, body?:string, timeoutSeconds?:number}} req
 * @param {Function} [transport] - (req) => { statusCode, json, headers }
 * @returns {{statusCode:number, json:any, headers:object}}
 */
/** The path only, never the query string - a key or token never belongs in a log line or an error message. */
function stripQuery(url) {
  var at = String(url).indexOf("?");
  return at >= 0 ? url.slice(0, at) : url;
}

/** $os.getenv, or "" outside PocketBase (plain Node has no $os at all). */
function transportMode() {
  if (typeof $os === "undefined" || !$os || !$os.getenv) return "";
  return $os.getenv("GG_ADAPTER_TRANSPORT_MODE") || "";
}

function request(req, transport) {
  var headers = { "User-Agent": USER_AGENT };
  var extra = req.headers || {};
  for (var k in extra) {
    if (Object.prototype.hasOwnProperty.call(extra, k)) headers[k] = extra[k];
  }
  var call = {
    url: req.url,
    method: req.method || "GET",
    headers: headers,
    body: req.body,
    timeoutSeconds: req.timeoutSeconds || DEFAULT_TIMEOUT_SECONDS,
  };

  if (transport) return transport(call);

  var mode = transportMode();
  var noHttp = typeof $http === "undefined";

  // globalThis.__adapterTransport is only ever honoured in a test-shaped
  // environment - GG_ADAPTER_TRANSPORT_MODE set (pb/scripts/check.sh), or
  // no $http binding at all (pb/scripts/check-adapters.mjs, plain Node) -
  // never in an ordinary request, so a stray global could not silently
  // hijack a real call even if goja's per-request isolation ever slipped.
  if ((mode || noHttp) && typeof globalThis !== "undefined" && globalThis.__adapterTransport) {
    return globalThis.__adapterTransport(call);
  }

  if (mode === "fixture") {
    var fixtures = require(__hooks + "/adapters/fixture_transport.js");
    return fixtures.respond(call);
  }

  if (mode) {
    throw new Error(
      "adapter transport disabled for tests (GG_ADAPTER_TRANSPORT_MODE=" +
        mode +
        "): attempted " +
        call.method +
        " " +
        stripQuery(call.url)
    );
  }

  if (noHttp) {
    throw new Error(
      "No transport available for " +
        call.method +
        " " +
        stripQuery(call.url) +
        ": pass one explicitly, set globalThis.__adapterTransport, " +
        "or run inside PocketBase where $http exists."
    );
  }

  var res = $http.send({
    url: call.url,
    method: call.method,
    headers: call.headers,
    body: call.body,
    timeout: call.timeoutSeconds,
  });
  return { statusCode: res.statusCode, json: res.json, headers: res.headers, body: res.body };
}

/** A small in-request pause, honouring a source's rate limit. No-op outside PocketBase. */
function pause(milliseconds) {
  if (typeof sleep === "function") sleep(milliseconds);
}

/** Percent-encode a query value the way every adapter here needs it. */
function qs(params) {
  var parts = [];
  for (var key in params) {
    if (!Object.prototype.hasOwnProperty.call(params, key)) continue;
    var value = params[key];
    if (value === null || value === undefined || value === "") continue;
    parts.push(encodeURIComponent(key) + "=" + encodeURIComponent(String(value)));
  }
  return parts.join("&");
}

module.exports = {
  request: request,
  pause: pause,
  qs: qs,
  stripQuery: stripQuery,
  USER_AGENT: USER_AGENT,
  DEFAULT_TIMEOUT_SECONDS: DEFAULT_TIMEOUT_SECONDS,
};
