import * as React from "react"
import { cn } from "cn"
import * as RechartsPrimitive from "recharts"

/**
 * The chart shell, generated by shadcn and then cut back to DESIGN.md.
 *
 * What changed from the generated component, and why:
 *  - No `aspect-video`. A report chart is given its height by the page, so a
 *    16:9 box on a phone is a chart nobody can read.
 *  - The tooltip is the paper panel every other popup in the app is: a
 *    hairline edge, 4px radius and the one soft shadow. No ring, no rounded
 *    corners of its own, no `bg-popover` blur.
 *  - Tick labels are Space Mono at the micro-label size, and the tooltip's
 *    own label is the same tracked micro-text, so a chart reads as part of
 *    the page rather than as a widget dropped on it.
 *  - The legend is text. Colour swatches are gone: a legend that depends on
 *    telling two greys apart is not a legend (DESIGN.md, accessibility).
 *  - Colours come from `--chart-1` to `--chart-5` only, passed by the caller
 *    through `ChartConfig`, and there is no theme-per-series CSS block: the
 *    five tokens already redefine themselves for night mode.
 *
 * Recharts is imported here and nowhere else outside the report routes, so
 * it stays out of the entry chunk.
 */

export type ChartConfig = Record<
  string,
  {
    label?: React.ReactNode
    /** One of the five chart tokens, as `var(--chart-1)`. Nothing else. */
    color?: string
  }
>

type ChartContextProps = { config: ChartConfig }

const ChartContext = React.createContext<ChartContextProps | null>(null)

function useChart() {
  const context = React.useContext(ChartContext)
  if (!context) {
    throw new Error("useChart must be used within a <ChartContainer />")
  }
  return context
}

function ChartContainer({
  id,
  className,
  children,
  config,
  ...props
}: React.ComponentProps<"div"> & {
  config: ChartConfig
  children: React.ComponentProps<
    typeof RechartsPrimitive.ResponsiveContainer
  >["children"]
}) {
  const uniqueId = React.useId()
  const chartId = `chart-${id ?? uniqueId.replace(/:/g, "")}`

  return (
    <ChartContext.Provider value={{ config }}>
      <div
        data-slot="chart"
        data-chart={chartId}
        className={cn(
          "w-full",
          // Space Mono at the micro-label size on every axis tick.
          "[&_.recharts-cartesian-axis-tick_text]:fill-muted-foreground-2 [&_.recharts-cartesian-axis-tick_text]:font-mono [&_.recharts-cartesian-axis-tick_text]:text-[11px]",
          "[&_.recharts-cartesian-axis-line]:stroke-hairline [&_.recharts-cartesian-axis-tick-line]:stroke-transparent",
          "[&_.recharts-rectangle.recharts-tooltip-cursor]:fill-row-hover",
          "[&_.recharts-curve.recharts-tooltip-cursor]:stroke-hairline",
          "[&_.recharts-layer]:outline-hidden [&_.recharts-surface]:outline-hidden",
          className
        )}
        {...props}
      >
        <RechartsPrimitive.ResponsiveContainer>
          {children}
        </RechartsPrimitive.ResponsiveContainer>
      </div>
    </ChartContext.Provider>
  )
}

const ChartTooltip = RechartsPrimitive.Tooltip

type TooltipPayloadEntry = {
  dataKey?: string | number
  name?: string | number
  value?: number | string
  color?: string
  type?: string
}

/**
 * The paper panel: the bucket in tracked micro-text, then one line per
 * series with its label and its figure. `format` puts money through
 * `formatGBP`, which is why the value is never left to `toLocaleString`.
 */
function ChartTooltipContent({
  active,
  payload,
  label,
  className,
  labelFormatter,
  format,
}: {
  active?: boolean
  payload?: TooltipPayloadEntry[]
  label?: string | number
  className?: string
  labelFormatter?: (label: string) => string
  format?: (value: number, key: string) => string
}) {
  const { config } = useChart()
  if (!active || !payload?.length) return null

  const heading =
    typeof label === "string" && labelFormatter ? labelFormatter(label) : String(label ?? "")

  return (
    <div
      data-slot="chart-tooltip"
      className={cn(
        "min-w-36 rounded-[var(--radius)] border border-hairline bg-popover px-4 py-3 text-popover-foreground shadow-panel",
        className
      )}
    >
      {heading ? (
        <p className="font-mono text-[11px] leading-[1.4] font-bold tracking-[0.16em] text-muted-foreground uppercase">
          {heading}
        </p>
      ) : null}
      <ul className="mt-2 flex flex-col gap-1">
        {payload
          .filter((item) => item.type !== "none")
          .map((item, index) => {
            const key = String(item.dataKey ?? item.name ?? index)
            const value = typeof item.value === "number" ? item.value : Number(item.value ?? 0)
            return (
              <li key={key} className="flex items-baseline justify-between gap-6">
                <span className="text-[13px] text-muted-foreground">
                  {config[key]?.label ?? key}
                </span>
                <span className="tnum text-[15px] font-medium text-foreground">
                  {format ? format(value, key) : String(value)}
                </span>
              </li>
            )
          })}
      </ul>
    </div>
  )
}

const ChartLegend = RechartsPrimitive.Legend

/**
 * Text, not swatches. Each series is named in the order it is drawn, which
 * is the order the bars and lines sit in, so nothing depends on telling two
 * greys apart.
 */
function ChartLegendContent({
  className,
  payload,
  order,
}: {
  className?: string
  payload?: TooltipPayloadEntry[]
  /** The series keys in the order the caller declared them. */
  order?: string[]
}) {
  const { config } = useChart()
  if (!payload?.length) return null

  const entries = payload.filter((item) => item.type !== "none")
  // Recharts hands the payload back in its own order; the caller's is the
  // one that means something, so the primary series is named first.
  const sorted = order
    ? [...entries].sort(
        (left, right) =>
          order.indexOf(String(left.dataKey ?? left.name ?? "")) -
          order.indexOf(String(right.dataKey ?? right.name ?? ""))
      )
    : entries

  return (
    <div
      data-slot="chart-legend"
      className={cn("flex flex-wrap items-center gap-x-8 gap-y-2 pt-4", className)}
    >
      {sorted.map((item, index) => {
          const key = String(item.dataKey ?? item.name ?? index)
          return (
            <span
              key={key}
              className="font-mono text-[11px] leading-[1.4] font-bold tracking-[0.16em] text-muted-foreground uppercase"
            >
              {config[key]?.label ?? key}
            </span>
          )
      })}
    </div>
  )
}

export {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
  ChartLegend,
  ChartLegendContent,
}
