/**
 * Generated by scripts/trace-logo.mjs from design/brand/logo.png. Do not edit
 * by hand: rerun the script when the logo changes.
 *
 * Every path is a fill. The outline is drawn as a stroke beneath the fill
 * (`paint-order: stroke`) at the width given here, which is twice the
 * outline's thickness because half of a centred stroke hides under the fill.
 * View boxes include the outline, so a mark sized by height shows all of it.
 */

/** The lockup: the paper G and the volt G side by side. */
export const LOGO = {
  viewBox: "0 0 316.32 100",
  stroke: 11.28,
  paper: "M64.69 5.93L168.25 5.93L145.99 30.86L75.37 30.86L71.51 32.05L68.25 35.91L51.04 66.77L50.45 69.73L51.34 72.11L54.9 74.18L101.78 74.18L109.79 61.13L81.31 61.13L92.58 45.4L154.9 45.4L126.11 94.07L22.55 94.36L18.1 94.07L13.06 92.58L7.72 88.13L5.64 83.38L5.64 78.93L6.53 75.96L37.39 22.85L44.21 15.43L50.45 10.98L57.27 7.72Z",
  volt: "M240.95 5.64L310.68 5.93L287.24 30.86L212.17 30.86L209.5 31.75L205.93 35.61L197.33 51.04L187.24 67.06L186.35 69.14L186.65 71.51L187.83 73L190.8 74.18L240.65 73.89L248.37 60.83L218.99 60.83L230.27 45.4L298.81 45.4L267.06 94.07L156.97 94.07L149.55 91.39L145.99 88.43L143.03 82.79L143.03 78.34L143.92 75.67L172.7 25.82L180.71 16.32L188.43 10.68L193.18 8.31L200 6.23Z",
} as const

/** The volt G on its own, for the places a lockup would not fit. */
export const G = {
  viewBox: "0 0 179.46 100",
  stroke: 11.31,
  d: "M103.87 5.65L173.81 5.95L150.3 30.95L75 30.95L72.32 31.85L68.75 35.71L60.12 51.19L50 67.26L49.11 69.35L49.4 71.73L50.6 73.21L53.57 74.4L103.57 74.11L111.31 61.01L81.85 61.01L93.15 45.54L161.9 45.54L130.06 94.35L19.64 94.35L12.2 91.67L8.63 88.69L5.65 83.04L5.65 78.57L6.55 75.89L35.42 25.89L43.45 16.37L51.19 10.71L55.95 8.33L62.8 6.25Z",
} as const
